w6d5/cats/ninety-nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats
end

w6d5/cats/ninety-nine_cats/app/models/cat.rb
require 'action_view'

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    validates :birth_date, :color, :name, :sex, :description, presence: true
    validates :sex, inclusion: %w(M F)
    validates :color, inclusion: %w(black brown yellow white)

    def age
        time_ago_in_words(birth_date)
        #time_age_in_words(from_time)
    end

end

w6d5/cats/ninety-nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all   
        render :index 
    end

    def show
        @cat = Cat.find(params[:id])
        if @cat
            render :show
        else
            redirect_to :cats_url
        end
    end

    def new 
        
        render :new
    end

    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end
end

#params {name: ?, color: ?, sex: ?, desctription: ?}

w6d5/cats/ninety-nine_cats/app/views/cats/edit.html.erb
<h1>Edit cat</h1>

<form action="<%= cat_url(@cat) %>" method = 'post'>
<input type="hidden", name = "_method", value = "patch" >
    <label for="new_cat"> Name </label>
    <input type="text", name = "cat[name]", value = "<%=  @cat.name %>">

<br><br>
    <label for="new_cat_birth_date"> Birth Date </label>
    <input type="date", name = "cat[birth_date]", value = "<%=  @cat.birth_date %>" >
 
<br><br>
    <label for="new_cat_color">Color </label>
        <select name = "cat[color]", id="new_cat_color">
            <option  > Select One </option>
            <% %w(white black yellow brown).each do |color|  %>
            <option value="<%= color %> " <%= @cat.color == color ? 'selected' : '' %>>
            <%= color %>
            </option>
            <% end %>

        </select>
<br><br>
    <label for="new_cat_sex"> Sex </label>
        <input type="radio" name = "cat[sex]" value = "M" id='male'
        <%= @cat.sex == "M" ? "checked" : ""%> > 
        <label for="male"> Male</label>
        <input type="radio" name = "cat[sex]" value = "F" id='female'
         <%= @cat.sex == "F" ? "checked" : ""%> > 
        <label for="female"> Female</label>

<br><br>
    <label for="new_cat_description">Description </label>
        <textarea name="cat[description]" ><%= @cat.description %></textarea>

<br><br>
    <input type="submit", value = "Edit Cat">


</form>

w6d5/cats/ninety-nine_cats/app/views/cats/index.html.erb
<h1>All the cats</h1>

<ul>
    <% @cats.each do |cat| %>
    <li><%= cat.name %></li>
    <li><%= cat.birth_date %></li>
    <li><%= cat.color %></li>
    <li><%= cat.sex %></li>
    <li><%= cat.description %></li>
    <% end %>
</ul>

w6d5/cats/ninety-nine_cats/app/views/cats/new.html.erb
<h1>New cat</h1>

<form action="<%= cats_url %>" method = 'post'>
    <label for="new_cat"> Name </label>
    <input type="text", name = "cat[name]">

<br><br>
    <label for="new_cat_birth_date"> Birth Date </label>
    <input type="date", name = "cat[birth_date]">
<br><br>
    <label for="new_cat_color">Color </label>
        <select name = "cat[color]", id="new_cat_color">
            <option  disabled selected> Select One </option>
            <option  value = "black"> Black </option>
            <option  value = "white"> White</option>
            <option  value = "brown"> Brown</option>
            <option  value = "yellow"> Yellow</option>
        </select>
<br><br>
    <label for="new_cat_sex"> Sex </label>
        <input type="radio", name = "cat[sex]", value = "M", id='male'> 
        <label for="male"> Male</label>
        <input type="radio", name = "cat[sex]", value = "F", id='female'> 
        <label for="female"> Female</label>

<br><br>
    <label for="new_cat_description">Description </label>
        <textarea name="cat[description]" ></textarea>

<br><br>
    <input type="submit", value = "Add a cat">


</form>

w6d5/cats/ninety-nine_cats/app/views/cats/show.html.erb
<h1> <% @cat.name %> </h1>

<table>
    <tbody>
    <tr>
        <th> Attribute </th>  
        <th> Value </th>
    </tr>
    <tr>
        <td>name:</td> 
         <td> <%= @cat.name %></td>
    </tr>

    <tr>
        <td>birth_date: </td> 
        <td><%= @cat.send(:age) %></td>
    </tr>
 <!-- invoke the method named 'method_name'  send(method_name) -->
    <tr>
        <td>color:</td> 
         <td> <%= @cat.color %></td>
    </tr>

    <tr>
        <td>sex:</td> 
        <td> <%= @cat.sex %></td>
    </tr>

    <tr>
        <td>description: </td> 
        <td> <%= @cat.description %></td>
    </tr>


</tbody>


</table>